      SUBROUTINE BVALUE (X,Y,Z,BX,BY,BZ,B,IOPT,PARMOD,EXNAME,INNAME)
C
C  CALCULATES THE COMPONENTS OF THE LOCAL B VECTOR IN THE GEOMAGNETIC FIELD
C
C     LAST MODIFICATION:  OCT 16, 2019
C
C     AUTHOR:  N. SIVADAS
C
C      DIMENSION PARMOD(10)
C
C     EXNAME AND INNAME ARE NAMES OF SUBROUTINES FOR THE EXTERNAL AND INTERNAL
C     PARTS OF THE TOTAL FIELD, E.G., T96_01 AND IGRF_GSW_08
C
      COMMON /GEOPACK1/ A(12),DS3,BB(2),PSI,CC(18)
      
      CALL EXNAME (IOPT,PARMOD,PSI,X,Y,Z,BXGSW,BYGSW,BZGSW)
      CALL INNAME (X,Y,Z,HXGSW,HYGSW,HZGSW)

      BX=BXGSW+HXGSW
      BY=BYGSW+HYGSW
      BZ=BZGSW+HZGSW
      B=SQRT(BX**2+BY**2+BZ**2)
      RETURN
      END
      
      SUBROUTINE BRADIAL (X,Y,Z,BX,BY,BZ,BR,BTHETA,BPHI)
C
C  CONVERTS THE COMPONENTS OF THE LOCAL B VECTOR TO RADIAL
C
C     LAST MODIFICATION:  OCT 16, 2019
C
C     AUTHOR:  N. SIVADAS
C
C      DIMENSION PARMOD(10)
C
C     INPUT: X,Y,Z,BX,BY,BZ,B are CARTESIAN GSW
C     OUTPUT: 
      
      CALL BCARSP_08 (X,Y,Z,BX,BY,BZ,BR,BTHETA,BPHI)
            
      RETURN
      END